CREATE TABLE Campo (
    ID INTEGER,
    Designacao VARCHAR2(255) NOT NULL,
    Area NUMBER NOT NULL,
    CONSTRAINT CAMPO_AREA_CK CHECK (Area > 0),
    CONSTRAINT CAMPO_ID_PK PRIMARY KEY (ID)
);

CREATE TABLE Especie_Vegetal (
    ID INTEGER,
    Nome VARCHAR2(255) NOT NULL CONSTRAINT Especie_Vegetal_Nome_UQ UNIQUE,
    CONSTRAINT ESPECIE_VEGETAL_ID_PK PRIMARY KEY (ID)
);

CREATE TABLE Cultura (
    ID INTEGER,
    Especie_Vegetal_ID INTEGER,
    CONSTRAINT CULTURA_ESPECIE_VEGETAL_ID_FK FOREIGN KEY (Especie_Vegetal_ID) REFERENCES Especie_Vegetal(ID),
    CONSTRAINT CULTURA_ID_PK PRIMARY KEY (ID)
);

CREATE TABLE Cultura_Temporaria (
    Cultura_ID INTEGER,
    Ciclo_Vegetativo INTEGER NOT NULL,
    CONSTRAINT CULTURA_TEMPORARIA_CICLO_VEGETATIVO_CK CHECK (Ciclo_Vegetativo > 0 AND Ciclo_Vegetativo <= 12),
    CONSTRAINT CULTURA_TEMPORARIA_CULTURA_ID_PK PRIMARY KEY (Cultura_ID)
);

CREATE TABLE Cultura_Permanente (
    Cultura_ID INTEGER,
    CONSTRAINT CULTURA_PERMANENTE_CULTURA_ID_PK PRIMARY KEY (Cultura_ID)
);

CREATE TABLE Campo_Cultura (
    Campo_ID INTEGER,
    Cultura_ID INTEGER,
    Data_Inicio_Cultura DATE,
    Data_Fim_Cultura DATE,
    CONSTRAINT CAMPO_CULTURA_DATA_FIM_CULTURA_CK CHECK (Data_Fim_Cultura > Data_Inicio_Cultura),
    CONSTRAINT CAMPO_CULTURA_CAMPO_ID_FK FOREIGN KEY (Campo_ID) REFERENCES Campo(ID),
    CONSTRAINT CAMPO_CULTURA_CULTURA_ID_FK FOREIGN KEY (Cultura_ID) REFERENCES Cultura(ID),
    CONSTRAINT CAMPO_CULTURA_COMP_PK PRIMARY KEY (Campo_ID, Cultura_ID, Data_Inicio_Cultura)
);

CREATE TABLE Preco (
    Valor NUMBER(4,2),
    CONSTRAINT PRECO_VALOR_PK PRIMARY KEY (Valor)
);

CREATE TABLE Colheita (
    Especie_Vegetal_ID INTEGER,
    Data_Colheita DATE,
    Data_Validade DATE NOT NULL,
    Quantidade NUMBER NOT NULL,
    CONSTRAINT COLHEITA_QUANTIDADE_CK CHECK (Quantidade > 0),
    CONSTRAINT COLHEITA_DATA_VALIDADE_CK CHECK (Data_Validade > Data_Colheita),
    CONSTRAINT COLHEITA_ESPECIE_VEGETAL_ID_FK FOREIGN KEY (Especie_Vegetal_ID) REFERENCES Especie_Vegetal(ID),
    CONSTRAINT COLHEITA_COMP_PK PRIMARY KEY (Especie_Vegetal_ID, Data_Colheita)
);

CREATE TABLE Campo_Colheita (
    Campo_ID INTEGER,
    Especie_Vegetal_ID INTEGER,
    Data_Colheita DATE,
    CONSTRAINT CAMPO_COLHEITA_CAMPO_ID_FK FOREIGN KEY (Campo_ID) REFERENCES Campo(ID),
    CONSTRAINT CAMPO_COLHEITA_COLHEITA_COMP_FK FOREIGN KEY (Especie_Vegetal_ID, Data_Colheita) REFERENCES Colheita(Especie_Vegetal_ID, Data_Colheita),
    CONSTRAINT CAMPO_COLHEITA_COMP_PK PRIMARY KEY (Campo_ID, Especie_Vegetal_ID, Data_Colheita)
);

CREATE TABLE Tipo_Cliente (
    ID INTEGER,
    Designacao VARCHAR2(255) NOT NULL CONSTRAINT TIPO_CLIENTE_DESIGNACAO_UQ UNIQUE,
    CONSTRAINT TIPO_CLIENTE_ID_PK PRIMARY KEY (ID)
);

CREATE TABLE Localidade (
    ID INTEGER,
    Nome VARCHAR2(255) NOT NULL CONSTRAINT LOCALIDADE_NOME_UQ UNIQUE,
    CONSTRAINT LOCALIDADE_ID_PK PRIMARY KEY (ID)
);

CREATE TABLE Pais (
    ID INTEGER,
    Nome VARCHAR2(255) NOT NULL CONSTRAINT PAIS_NOME_UQ UNIQUE,
    CONSTRAINT PAIS_ID_PK PRIMARY KEY (ID)
);

CREATE TABLE Morada (
    ID INTEGER,
    Localidade_ID INTEGER NOT NULL,
    Pais_ID INTEGER NOT NULL,
    Nome_Rua VARCHAR2(255) NOT NULL,
    Numero_Porta INTEGER NOT NULL,
    Codigo_Postal VARCHAR(8) NOT NULL,
    CONSTRAINT MORADA_CODIGO_POSTAL_CK CHECK (Codigo_Postal LIKE '[0-9][0-9][0-9][0-9]-[0-9][0-9][0-9]'),
    CONSTRAINT MORADA_PAIS_ID_FK FOREIGN KEY (Pais_ID) REFERENCES Pais(ID),
    CONSTRAINT MORADA_LOCALIDADE_ID_FK FOREIGN KEY (Localidade_ID) REFERENCES Localidade(ID),
    CONSTRAINT MORADA_ID_PK PRIMARY KEY (ID)
);

CREATE TABLE Cliente (
    Codigo_Unico INTEGER,
    Tipo_Cliente_ID INTEGER NOT NULL,
    Morada_Correspondencia_ID INTEGER NOT NULL,
    Morada_Entrega_ID INTEGER NOT NULL,
    Nome VARCHAR2(255) NOT NULL,
    Numero_Fiscal VARCHAR(9) NOT NULL CONSTRAINT CLIENTE_NUMERO_FISCAL_UQ UNIQUE,
    Email VARCHAR2(255) NOT NULL CONSTRAINT CLIENTE_EMAIL_UQ UNIQUE,
    Plafond NUMBER NOT NULL,
    CONSTRAINT CLIENTE_EMAIL_CK CHECK (Email LIKE '%@%.%'),
    CONSTRAINT CLIENTE_NUMERO_FISCAL_CK CHECK (Numero_Fiscal LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'),
    CONSTRAINT CLIENTE_MORADA_ENTREGA_ID_FK FOREIGN KEY (Morada_Entrega_ID) REFERENCES Morada(ID),
    CONSTRAINT CLIENTE_MORADA_CORRESPONDENCIA_ID_FK FOREIGN KEY (Morada_Correspondencia_ID) REFERENCES Morada(ID),
    CONSTRAINT CLIENTE_TIPO_CLIENTE_ID_FK FOREIGN KEY (Tipo_Cliente_ID) REFERENCES Tipo_Cliente(ID),
    CONSTRAINT CLIENTE_CODIGO_UNICO_PK PRIMARY KEY (Codigo_Unico)
);

CREATE TABLE Estado (
    ID INTEGER,
    Designacao VARCHAR2(255) NOT NULL CONSTRAINT ESTADO_DESIGNACAO_UQ UNIQUE,
    CONSTRAINT ESTADO_ID_PK PRIMARY KEY (ID)
);

CREATE TABLE Encomenda (
    ID INTEGER,
    Cliente_Codigo_Unico INTEGER NOT NULL,
    Estado_ID INTEGER NOT NULL,
    Data_Encomenda DATE NOT NULL,
    Data_Limite_Pagamento DATE NOT NULL,
    CONSTRAINT ENCOMENDA_DATA_LIMITE_PAGAMENTO_CK CHECK (Data_Limite_Pagamento >= Data_Encomenda),
    CONSTRAINT ENCOMENDA_ESTADO_ID_FK FOREIGN KEY (Estado_ID) REFERENCES Estado(ID),
    CONSTRAINT ENCOMENDA_CLIENTE_CODIGO_UNICO_FK FOREIGN KEY (Cliente_Codigo_Unico) REFERENCES Cliente(Codigo_Unico),
    CONSTRAINT ENCOMENDA_ID_PK PRIMARY KEY (ID)
);

CREATE TABLE Pagamento (
    Cliente_Codigo_Unico INTEGER,
    Encomenda_ID INTEGER,
    Data_Pagamento DATE NOT NULL,
    CONSTRAINT PAGAMENTO_ENCOMENDA_ID_FK FOREIGN KEY (Encomenda_ID) REFERENCES Encomenda(ID),
    CONSTRAINT PAGAMENTO_CLIENTE_CODIGO_UNICO_FK FOREIGN KEY (Cliente_Codigo_Unico) REFERENCES Cliente(Codigo_Unico),
    CONSTRAINT PAGAMENTO_COMP_PK PRIMARY KEY (Cliente_Codigo_Unico, Encomenda_ID)
);

CREATE TABLE Incidente (
    Cliente_Codigo_Unico INTEGER,
    Encomenda_ID INTEGER,
    Data_Incumprimento DATE NOT NULL,
    Data_Sanamento DATE NOT NULL,
    CONSTRAINT INCIDENTE_DATA_SANAMENTO_CK CHECK (Data_Sanamento >= Data_Incumprimento),
    CONSTRAINT INCIDENTE_COMP_PK PRIMARY KEY (Cliente_Codigo_Unico, Encomenda_ID)
);

CREATE TABLE Encomenda_Colheita (
    Encomenda_ID INTEGER,
    Especie_Vegetal_ID INTEGER,
    Data_Colheita DATE,
    Quantidade NUMBER NOT NULL,
    CONSTRAINT ENCOMENDA_COLHEITA_QUANTIDADE_CK CHECK (Quantidade > 0),
    CONSTRAINT ENCOMENDA_COLHEITA_COLHEITA_COMP_FK FOREIGN KEY (Especie_Vegetal_ID, Data_Colheita) REFERENCES Colheita(Especie_Vegetal_ID, Data_Colheita),
    CONSTRAINT ENCOMENDA_COLHEITA_ENCOMENDA_ID_FK FOREIGN KEY (Encomenda_ID) REFERENCES Encomenda(ID),
    CONSTRAINT ENCOMENDA_COLHEITA_COMP_PK PRIMARY KEY (Encomenda_ID, Especie_Vegetal_ID, Data_Colheita)
);