@startuml Quinta-Manutenção

/'TODO #1:- Verificar se a Designação de um Campo é única e se estas 
devem seguir um conjunto de regras;'/
/'TODO #2:- Determinar o valor minímo de uma qualquer Área;'/
/'Constraints:- [[Area, CHECK(Area > Mínimo)]]'/
entity Campo {
    * ID: INTEGER <<PK>>
    --
    Designacao: VARCHAR2(255) NOT NULL
    Area: NUMBER NOT NULL
}

/'Triggers:-
    #1: Verificar que uma Cultura não é simultaneamente uma Cultura_Temporaria
    e Cultura_Permanente;'/
entity Cultura {
    * ID: INTEGER <<PK>>
    --
}

/'Constraints:- [[Campo_ID, Data_Inicio_Cultura, UNIQUE(Campo_ID, Data_Inicio_Cultura)], 
[Data_Fim_Cultura, CHECK(Data_Fim_Cultura < Data_Inicio_Cultura)]]'/
entity Plantacao {
    * Campo_ID: INTEGER <<PK>> <<FK>>
    * Cultura_ID: INTEGER <<PK>> <<FK>>
    --
    Data_Inicio_Cultura: DATE <<PK>>
    Data_Fim_Cultura: DATE
}

/'Constraints:- [[Quantidade, CHECK(Quantidade > 0)]]'/
entity Accao {
    * ID: INTEGER <<PK>>
    --

    Campo_ID: INTEGER <<FK>>
    Cultura_ID: INTEGER <<FK>>
    Data_Accao: DATE NOT NULL
    Quantidade: NUMBER NOT NULL
}

entity Metodo_Distribuicao {
    * ID: INTEGER <<PK>>
    --
    Designacao: VARCHAR2(255) NOT NULL UNIQUE
}

entity Rega {
    * Accao_ID: INTEGER <<PK>>
    --
    Metodo_Distribuicao_ID: INTEGER <<FK>> NOT NULL
}

entity Aplicacao_Produto {
    * Accao_ID: INTEGER <<PK>>
    --
    Produto_ID: INTEGER <<FK>> NOT NULL
    Metodo_Distribuicao_ID: INTEGER <<FK>> NOT NULL
}

entity Produto {
    * ID: INTEGER <<PK>>
    --
    Tipo_produto_ID: INTEGER <<FK>> NOT NULL
    Fornecedor: VARCHAR2(255) NOT NULL
    Ficha_Tecnica_ID: INTEGER <<FK>> NOT NULL UNIQUE
    Nome: VARCHAR2(255) NOT NULL UNIQUE
}


entity Tipo_Produto {
    * ID: INTEGER <<PK>>
    --
    Tipo: VARCHAR2(255) NOT NULL UNIQUE
}

entity Ficha_Tecnica {
    * ID: INTEGER <<PK>>
    --
    Humidade: NUMBER
    pH: NUMBER
    Peso_Especifico: NUMBER
    Formulacao_Peletizada: INTEGER
}

entity Ficha_Tecnica_Substancia {
    * Ficha_Tecnica_ID: INTEGER <<PK>> <<FK>>
    * Substancia_ID: INTEGER <<PK>> <<FK>>
    --
    QuantidadePerc: NUMBER NOT NULL
}

entity Substancia {
    * ID: INTEGER <<PK>>
    --
    Nome: VARCHAR2(255) NOT NULL UNIQUE
    Unidade: VARCHAR2(255) NOT NULL
}

entity Tipo_Cultura {
    * ID: INTEGER <<PK>>
    --
    Designacao: VARCHAR2(255) NOT NULL UNIQUE
}

entity Plano {
    * ID: INTEGER <<PK>>
    --
    Periodicidade_ID: INTEGER <<FK>> NOT NULL
    Campo_ID: INTEGER <<FK>> NOT NULL
    Cultura_ID: INTEGER <<FK>> NOT NULL
    Quantidade: NUMBER NOT NULL
}

entity Periocidade {
    * ID: INTEGER <<PK>>
    --
    Designacao: VARCHAR2(255) NOT NULL UNIQUE
}

entity Plano_Rega {
    * Plano_ID: INTEGER <<PK>> <<FK>>
    --
}

entity Plano_Aplicacao_Produto {
    * Plano_ID: INTEGER <<PK>> <<FK>>
    --
}

Campo ||-d-|{ Plantacao

Cultura ||-r-|{ Plantacao
Cultura }|-l-|| Tipo_Cultura 

Plantacao ||-r-|{ Accao
Plantacao ||-d-|{ Plano

Accao ||--d--|| Rega
Accao ||--d--|| Aplicacao_Produto

Metodo_Distribuicao ||-r-o{ Rega
Metodo_Distribuicao ||-l-o{ Aplicacao_Produto

Tipo_Produto ||-d-o{ Produto

Produto ||-d-|| Ficha_Tecnica
Produto ||--u--o{ Aplicacao_Produto

Ficha_Tecnica ||-d-|{ Ficha_Tecnica_Substancia

Substancia ||-u-|{ Ficha_Tecnica_Substancia

Periocidade ||-r-o{ Plano

Plano_Rega ||-u-|| Plano

Plano_Aplicacao_Produto ||-u-|| Plano

@enduml