CREATE TABLE Campo (
    ID INTEGER,
    Designacao VARCHAR2(255) NOT NULL,
    Area NUMBER NOT NULL,
    Hectares INTEGER NOT NULL,
    CONSTRAINT CAMPO_HECTARES_CK CHECK(Hectares > 0),
    CONSTRAINT CAMPO_AREA_CK CHECK (Area > 0),
    CONSTRAINT CAMPO_ID_PK PRIMARY KEY (ID)
);

CREATE TABLE Especie_Vegetal (
    ID INTEGER,
    Nome VARCHAR2(255) NOT NULL CONSTRAINT Especie_Vegetal_Nome_UQ UNIQUE,
    CONSTRAINT ESPECIE_VEGETAL_ID_PK PRIMARY KEY (ID)
);

CREATE TABLE Tipo_Cultura(
    ID INTEGER,
    Designacao VARCHAR2(255) NOT NULL CONSTRAINT TIPO_CULTURA_DESIGNACAO_UQ UNIQUE,
    CONSTRAINT TIPO_CULTURA_ID_PK PRIMARY KEY(ID)
);

CREATE TABLE Cultura (
    ID INTEGER,
    Especie_Vegetal_ID INTEGER,
    Tipo_Cultura_ID INTEGER,
    CONSTRAINT CULTURA_ESPECIE_VEGETAL_ID_FK FOREIGN KEY (Especie_Vegetal_ID) REFERENCES Especie_Vegetal(ID),
    CONSTRAINT CULTURA_TIPO_CULTURA_ID_FK FOREIGN KEY(Tipo_Cultura_ID) REFERENCES Tipo_Cultura(ID),
    CONSTRAINT CULTURA_ID_PK PRIMARY KEY (ID)
);

CREATE TABLE Cultura_Temporaria (
    Cultura_ID INTEGER,
    Ciclo_Vegetativo INTEGER NOT NULL,
    CONSTRAINT CULTURA_TEMPORARIA_CICLO_VEGETATIVO_CK CHECK (Ciclo_Vegetativo > 0 AND Ciclo_Vegetativo <= 12),
    CONSTRAINT CULTURA_TEMPORARIA_CULTURA_ID_FK FOREIGN KEY (Cultura_ID) REFERENCES Cultura(ID),
    CONSTRAINT CULTURA_TEMPORARIA_CULTURA_ID_PK PRIMARY KEY (Cultura_ID)
);

CREATE TABLE Cultura_Permanente (
    Cultura_ID INTEGER,
    CONSTRAINT CULTURA_PERMANENTE_CULTURA_ID_FK FOREIGN KEY (Cultura_ID) REFERENCES Cultura(ID),
    CONSTRAINT CULTURA_PERMANENTE_CULTURA_ID_PK PRIMARY KEY (Cultura_ID)
);

CREATE TABLE Plantacao (
    Campo_ID INTEGER,
    Cultura_ID INTEGER,
    Data_Inicio_Cultura DATE NOT NULL,
    Data_Fim_Cultura DATE,
    CONSTRAINT PLANTACAO_DATA_INICIO_CK CHECK (TO_CHAR(Data_Inicio_Cultura, 'YYYY-MM-DD') < TO_CHAR(Data_Fim_Cultura, 'YYYY-MM-DD')),
    CONSTRAINT PLANTACAO_CAMPO_ID_FK FOREIGN KEY (Campo_ID) REFERENCES Campo(ID),
    CONSTRAINT PLANTACAO_CULTURA_ID_FK FOREIGN KEY (Cultura_ID) REFERENCES Cultura(ID),
    CONSTRAINT PLANTACAO_COMP_PK PRIMARY KEY (Campo_ID,Cultura_ID)
);


CREATE TABLE Accao(
    ID INTEGER,
    Campo_ID INTEGER,
    Cultura_ID INTEGER,
    Data_Accao DATE NOT NULL,
    CONSTRAINT ACCAO_PLANTACAO_COMP_FK FOREIGN KEY (Campo_ID, Cultura_ID) REFERENCES Plantacao(Campo_ID, Cultura_ID),
    CONSTRAINT ACCAO_ID_PK PRIMARY KEY (ID) 
);

CREATE TABLE Colheita (
    Accao_ID INTEGER,
    Especie_Vegetal_ID INTEGER NOT NULL,
    Quantidade NUMBER NOT NULL,
    Preco NUMBER NOT NULL,
    CONSTRAINT COLHEITA_QUANTIDADE_CK CHECK (Quantidade > 0),
    CONSTRAINT COLHEITA_ESPECIE_VEGETAL_ID_FK FOREIGN KEY (Especie_Vegetal_ID) REFERENCES Especie_Vegetal(ID),
    CONSTRAINT COLHEITA_ACCAO_ID_FK FOREIGN KEY (Accao_ID) REFERENCES Accao(ID),
    CONSTRAINT COLHEITA_ACCAO_ID_PK PRIMARY KEY (Accao_ID)
);

CREATE TABLE Tipo_Cliente (
    ID INTEGER,
    Designacao VARCHAR2(255) NOT NULL CONSTRAINT TIPO_CLIENTE_DESIGNACAO_UQ UNIQUE,
    CONSTRAINT TIPO_CLIENTE_ID_PK PRIMARY KEY (ID)
);

CREATE TABLE Localidade (
    ID INTEGER,
    Nome VARCHAR2(255) NOT NULL CONSTRAINT LOCALIDADE_NOME_UQ UNIQUE,
    CONSTRAINT LOCALIDADE_ID_PK PRIMARY KEY (ID)
);

CREATE TABLE Pais (
    ID INTEGER,
    Nome VARCHAR2(255) NOT NULL CONSTRAINT PAIS_NOME_UQ UNIQUE,
    CONSTRAINT PAIS_ID_PK PRIMARY KEY (ID)
);

CREATE TABLE Morada (
    ID INTEGER,
    Localidade_ID INTEGER NOT NULL,
    Pais_ID INTEGER NOT NULL,
    Nome_Rua VARCHAR2(255) NOT NULL,
    Numero_Porta INTEGER NOT NULL,
    Codigo_Postal VARCHAR(8) NOT NULL,
    CONSTRAINT MORADA_NUMERO_PORTA_CK CHECK (Numero_Porta > 0),
    --CONSTRAINT MORADA_CODIGO_POSTAL_CK CHECK (Codigo_Postal LIKE '[0-9][0-9][0-9][0-9]-[0-9][0-9][0-9]'),
    CONSTRAINT MORADA_PAIS_ID_FK FOREIGN KEY (Pais_ID) REFERENCES Pais(ID),
    CONSTRAINT MORADA_LOCALIDADE_ID_FK FOREIGN KEY (Localidade_ID) REFERENCES Localidade(ID),
    CONSTRAINT MORADA_ID_PK PRIMARY KEY (ID)
);

CREATE TABLE Cliente (
    Codigo_Unico INTEGER,
    Tipo_Cliente_ID INTEGER NOT NULL,
    Morada_Correspondencia_ID INTEGER NOT NULL,
    Morada_Entrega_ID INTEGER NOT NULL,
    Nome VARCHAR2(255) NOT NULL,
    Numero_Fiscal INTEGER NOT NULL CONSTRAINT CLIENTE_NUMERO_FISCAL_UQ UNIQUE,
    Email VARCHAR2(255) NOT NULL CONSTRAINT CLIENTE_EMAIL_UQ UNIQUE,
    Plafond NUMBER NOT NULL,
    Numero_Total_Encomendas INTEGER NOT NULL,
    Valor_Total_Encomendas INTEGER NOT NULL, 
    CONSTRAINT CLIENTE_EMAIL_CK CHECK (Email LIKE '%@%.%'),
    CONSTRAINT CLIENTE_NUMERO_FISCAL_CK CHECK (Numero_Fiscal > 99999999 AND Numero_Fiscal < 1000000000),
    CONSTRAINT CLIENTE_MORADA_ENTREGA_ID_FK FOREIGN KEY (Morada_Entrega_ID) REFERENCES Morada(ID),
    CONSTRAINT CLIENTE_MORADA_CORRESPONDENCIA_ID_FK FOREIGN KEY (Morada_Correspondencia_ID) REFERENCES Morada(ID),
    CONSTRAINT CLIENTE_TIPO_CLIENTE_ID_FK FOREIGN KEY (Tipo_Cliente_ID) REFERENCES Tipo_Cliente(ID),
    CONSTRAINT CLIENTE_CODIGO_UNICO_PK PRIMARY KEY (Codigo_Unico)
);

CREATE TABLE Encomenda (
    ID INTEGER,
    Cliente_Codigo_Unico INTEGER NOT NULL,
    Data_Encomenda DATE NOT NULL,
    Data_Limite_Pagamento DATE NOT NULL,
    Data_Pagamento DATE,
    CONSTRAINT ENCOMENDA_CLIENTE_CODIGO_UNICO_FK FOREIGN KEY (Cliente_Codigo_Unico) REFERENCES Cliente(Codigo_Unico),
    CONSTRAINT ENCOMENDA_ID_PK PRIMARY KEY (ID)
);


CREATE TABLE Incidente (
    Cliente_Codigo_Unico INTEGER,
    Encomenda_ID INTEGER,
    Data_Incumprimento DATE NOT NULL,
    CONSTRAINT INCIDENTE_ENCOMENDA_ID_FK FOREIGN KEY (Encomenda_ID) REFERENCES Encomenda(ID),
    CONSTRAINT INCIDENTE_CLIENTE_CODIGO_UNICO_FK FOREIGN KEY (Cliente_Codigo_Unico) REFERENCES Cliente(Codigo_Unico),
    CONSTRAINT INCIDENTE_COMP_PK PRIMARY KEY (Cliente_Codigo_Unico, Encomenda_ID)
);

CREATE TABLE Encomenda_Especie_Vegetal(
    Encomenda_ID INTEGER,
    Especie_Vegetal_ID INTEGER,
    Quantidade NUMBER NOT NULL,
    Preco NUMBER NOT NULL,
    CONSTRAINT ENCOMENDA_ESPECIE_VEGETAL_ENCOMENDA_ID_FK FOREIGN KEY (Encomenda_ID) REFERENCES Encomenda(ID),
    CONSTRAINT ENCOMENDA_ESPECIE_VEGETAL_ESPECIE_VEGETAL_ID_FK FOREIGN KEY (Especie_Vegetal_ID) REFERENCES Especie_Vegetal(ID),
    CONSTRAINT ENCOMENDA_ESPECIE_VEGETAL_COMP_PK PRIMARY KEY (Encomenda_ID, Especie_Vegetal_ID)
);


CREATE TABLE Metodo_Distribuicao(
    ID INTEGER,
    Designacao VARCHAR2(255) NOT NULL CONSTRAINT METODO_DISTRIBUICAO_DESIGNACAO_UQ UNIQUE,
    CONSTRAINT METODO_DISTRIBUICAO_ID_PK PRIMARY KEY (ID)
);

CREATE TABLE Rega (
    Accao_ID INTEGER,
    Metodo_Distribuicao_ID INTEGER NOT NULL,
    Quantidade NUMBER NOT NULL,
    CONSTRAINT REGA_QUANTIDADE_CK CHECK (Quantidade > 0),
    CONSTRAINT REGA_ACCAO_ID_FK FOREIGN KEY (Accao_ID) REFERENCES Accao(ID),
    CONSTRAINT REGA_METODO_DISTRIBUICAO_ID_FK FOREIGN KEY (Metodo_Distribuicao_ID) REFERENCES Metodo_Distribuicao(ID),
    CONSTRAINT REGA_ACCAO_ID_PK PRIMARY KEY (Accao_ID)
);

CREATE TABLE Classificacao(
    ID INTEGER,
    Designacao VARCHAR2(255) NOT NULL CONSTRAINT CLASSIFICACAO_DESIGNCAO_UQ UNIQUE,
    CONSTRAINT CLASSIFICACAO_ID_PK PRIMARY KEY (ID)
);


CREATE TABLE Substancia(
    ID INTEGER,
    Nome VARCHAR2(255) NOT NULL CONSTRAINT SUBSTANCIA_NOME_UQ UNIQUE,
    CONSTRAINT SUBSTANCIA_ID_PK PRIMARY KEY (ID)
);


CREATE TABLE Formulacao(
    ID INTEGER,
    Designacao VARCHAR2(255) NOT NULL CONSTRAINT FORMULACAO_DESGNCAO_UQ UNIQUE,
    CONSTRAINT FORMULACAO_ID_PK PRIMARY KEY (ID)
);

CREATE TABLE Ficha_Tecnica(
    ID INTEGER,
    Humidade NUMBER,
    pH NUMBER,
    Peso_Especifico NUMBER,
    Formulacao_Peletizada INTEGER,
    CONSTRAINT FICHA_TECNICA_PK PRIMARY KEY(ID)
);

CREATE TABLE Ficha_Tecnica_Substancia(
    Ficha_Tecnica_ID INTEGER,
    Substancia_ID INTEGER,
    Quantidade NUMBER NOT NULL,
    CONSTRAINT FICHA_TECNICA_SUBSTANCIA_FICHA_TECNICA_ID_FK FOREIGN KEY (Ficha_Tecnica_ID) REFERENCES Ficha_Tecnica(ID),
    CONSTRAINT FICHA_TECNICA_SUBSTANCIA_ID_FK FOREIGN KEY (Substancia_ID) REFERENCES Substancia(ID)
);

CREATE TABLE Produto(
    ID INTEGER,
    Classificacao_ID INTEGER NOT NULL,
    Formulacao_ID INTEGER NOT NULL,
    Ficha_Tecnica_ID INTEGER NOT NULL CONSTRAINT PRODUTO_FICHA_TECNICA_ID_UQ UNIQUE,
    Nome VARCHAR2(255) NOT NULL CONSTRAINT PRODUTO_NOME_UQ UNIQUE,
    CONSTRAINT PRODUTO_CLASSIFICACAO_ID_FK FOREIGN KEY (Classificacao_ID) REFERENCES Classificacao(ID),
    CONSTRAINT PRODUTO_FORMUALACAO_ID_FK FOREIGN KEY (Formulacao_ID) REFERENCES Formulacao(ID),
    CONSTRAINT PRODUTO_FICHA_TECNICA_ID_FK FOREIGN KEY (Ficha_Tecnica_ID) REFERENCES Ficha_Tecnica(ID),
    CONSTRAINT PRODUTO_ID_PK PRIMARY KEY (ID)
);

CREATE TABLE Aplicacao_Produto(
    Accao_ID INTEGER,
    Produto_ID INTEGER NOT NULL,
    Metodo_Distribuicao_ID INTEGER NOT NULL,
    Quantidade NUMBER NOT NULL,
    CONSTRAINT APLICACAO_PRODUTO_QUANTIDADE_CK CHECK (Quantidade > 0),
    CONSTRAINT APLICACAO_PRODUTO_ACCAO_ID_FK FOREIGN KEY (Accao_ID) REFERENCES Accao(ID),
    CONSTRAINT APLICACAO_PRODUTO_PRODUTO_ID_FK FOREIGN KEY (Produto_ID) REFERENCES Produto(ID),
    CONSTRAINT APLICACAO_PRODUTO_METOFO_DISTRIBUICAO_ID_FK FOREIGN KEY (Metodo_Distribuicao_ID) REFERENCES Metodo_Distribuicao(ID),
    CONSTRAINT APLICACAO_PRODUTO_ACCAO_ID_PK PRIMARY KEY (Accao_ID)  
); 

CREATE TABLE Periodicidade(
    ID INTEGER, 
    Designacao VARCHAR2(255) NOT NULL CONSTRAINT PERIODICIDADE_DESIGNACAO_UQ UNIQUE,
    CONSTRAINT PERIODICIDADE_ID_PK PRIMARY KEY(ID)
);


CREATE TABLE Plano(
    ID INTEGER,
    Periodicidade_ID INTEGER NOT NULL,
    Campo_ID INTEGER NOT NULL,
    Cultura_ID INTEGER NOT NULL,
    Quantidade NUMBER NOT NULL,
    CONSTRAINT PLANO_PERIODICIDADE_ID_FK FOREIGN KEY (Periodicidade_ID) REFERENCES Periodicidade(ID),
    CONSTRAINT PLANO_COMP_FK FOREIGN KEY (Campo_ID,Cultura_ID) REFERENCES Plantacao(Campo_ID,Cultura_ID), 
    CONSTRAINT PLANO_ID_PK PRIMARY KEY (ID)
);

CREATE TABLE Plano_Rega(
    Plano_ID INTEGER,
    CONSTRAINT PLANO_REGA_PLANO_ID_FK FOREIGN KEY (Plano_ID) REFERENCES Plano(ID),
    CONSTRAINT PLANO_REGA_PLANO_ID_PK PRIMARY KEY (Plano_ID)
); 

CREATE TABLE Plano_Aplicacao_Produto(
    Plano_ID INTEGER,
    CONSTRAINT PLANO_APLICACAO_PRODUTO_ID_FK FOREIGN KEY(Plano_ID) REFERENCES Plano(ID),
    CONSTRAINT PLANO_APLICACAO_PRODUTO_ID_PK PRIMARY KEY(Plano_ID)
);

CREATE TABLE Tipo_Sensor(
    ID INTEGER,
    Designacao VARCHAR2(255) NOT NULL CONSTRAINT TIPO_SENSOR_DESIGNACAO_UQ UNIQUE,
    CONSTRAINT TIPO_SENSOR_ID_PK PRIMARY KEY (ID)
);

CREATE TABLE Sensor(
    ID INTEGER,
    Tipo_Sensor_ID INTEGER,
    CONSTRAINT SENSOR_TIPO_SENSOR_ID_FK FOREIGN KEY (Tipo_Sensor_ID) REFERENCES Tipo_Sensor(ID),
    CONSTRAINT SENSOR_ID_PK PRIMARY KEY (ID)
);

CREATE TABLE Leitura(
    Campo_ID INTEGER,
    Cultura_ID INTEGER,
    Data_Leitura DATE,
    Sensor_ID INTEGER NOT NULL,
    Valor NUMBER NOT NULL,
    CONSTRAINT LEITURA_COMP_FK FOREIGN KEY (Campo_ID, Cultura_ID) REFERENCES Plantacao(Campo_ID, Cultura_ID),
    CONSTRAINT LEITURA_SENSOR_ID_FK FOREIGN KEY (Sensor_ID) REFERENCES Sensor(ID),
    CONSTRAINT LEITURA_COMP_PK PRIMARY KEY (Campo_ID,Cultura_ID,Data_Leitura)
);