@startuml Quinta-Manutenção

/'TODO #1:- Verificar se a Designação de um Campo é única e se estas 
devem seguir um conjunto de regras;'/
/'TODO #2:- Determinar o valor minímo de uma qualquer Área;'/
/'Constraints:- [[Area, CHECK(Area > Mínimo)]]'/
entity Campo {
    * ID: INTEGER <<PK>>
    --
    Designacao: VARCHAR2(255) NOT NULL
    Area: NUMBER NOT NULL
}

/'Triggers:-
    #1: Verificar que uma Cultura não é simultaneamente uma Cultura_Temporaria
    e Cultura_Permanente;'/
entity Cultura {
    * ID: INTEGER <<PK>>
    --
}

/'Contraints:- [[Ciclo_Vegetativo, CHECK(Ciclo_Vegetativo > 0)], 
[Ciclo_Vegetativo, CHECK(Ciclo_Vegetativo < 12)]]'/
entity Cultura_Temporaria {
    * Cultura_ID: INTEGER <<PK>> <<FK>>
    --
    Ciclo_Vegetativo: INTEGER NOT NULL
}

entity Cultura_Permanente {
    * Cultura_ID: INTEGER <<PK>> <<FK>>
}

/'Constraints:- [[Campo_ID, Data_Inicio_Cultura, UNIQUE(Campo_ID, Data_Inicio_Cultura)], 
[Data_Fim_Cultura, CHECK(Data_Fim_Cultura < Data_Inicio_Cultura)]]'/
entity Plantacao {
    * ID: INTEGER <<PK>>
    * Campo_ID: INTEGER <<PK>> <<FK>>
    * Cultura_ID: INTEGER <<PK>> <<FK>>
    --
    Data_Inicio_Cultura: DATE <<PK>>
    Data_Fim_Cultura: DATE
}

/'Constraints:- [[Quantidade, CHECK(Quantidade > 0)]]'/
entity Accao {
    * ID: INTEGER <<PK>>
    *Plantacao_ID: INTEGER <<PK>> <<FK>>
    --
    Data_Accao: DATE NOT NULL
    Quantidade: NUMBER NOT NULL
}

entity Metodo_Distribuicao {
    * ID: INTEGER <<PK>>
    --
    Designacao: VARCHAR2(255) NOT NULL UNIQUE
}

entity Rega {
    * Accao_ID: INTEGER <<PK>>
    --
    Metodo_Distribuicao_ID: INTEGER <<FK>> NOT NULL
}

entity Adubacao {
    * Accao_ID: INTEGER <<PK>>
    --
    Metodo_Distribuicao_ID: INTEGER <<FK>> NOT NULL
}

entity Categoria{
     * ID: INTEGER <<PK>>
    --
    Designacao: VARCHAR2(255) NOT NULL
}

entity Aplicacao_Fator_Producao {
    * Accao_ID: INTEGER <<PK>>
    --
    Fator_Producao_ID: INTEGER <<FK>> NOT NULL
    Metodo_Distribuicao_ID: INTEGER <<FK>> NOT NULL
}

entity Restricao {
    Campo_ID: INTEGER <<PK>> <<FK>>
    Fator_Producao_ID: INTEGER <<PK>> <<FK>>
    Inicio_Restricao: DATE <<PK>>
    Fim_Restricao: DATE <<PK>>
}

entity Fator_Producao {
    * ID: INTEGER <<PK>>
    *Tipo_Fator_Producao_ID: INTEGER <<FK>>
    --
    Ficha_Tecnica_ID: INTEGER <<FK>> NOT NULL UNIQUE
    Nome: VARCHAR2(255) NOT NULL UNIQUE
}


entity Tipo_Fator_Producao {
    * ID: INTEGER <<PK>>
    --
    Designacao: VARCHAR2(255) NOT NULL UNIQUE
}

entity Ficha_Tecnica {
    * ID: INTEGER <<PK>>
    --
    Fornecedor: VARCHAR2(255) NOT NULL,
    Humidade: FLOAT
    pH: FLOAT
    Peso_Especifico: FLOAT
    Formulacao_Peletizada: FLOAT
}

entity Ficha_Tecnica_Substancia {
    * Ficha_Tecnica_ID: INTEGER <<PK>> <<FK>>
    * Substancia_ID: INTEGER <<PK>> <<FK>>
    --
    QuantidadePerc: NUMBER NOT NULL
}

entity Substancia {
    * ID: INTEGER <<PK>>
    --
    Nome: VARCHAR2(255) NOT NULL UNIQUE
    Categoria_ID: INTEGER <<FK>> NOT NULL
    Unidade: VARCHAR2(255) NOT NULL
}

entity Plano {
    * ID: INTEGER <<PK>>
    --
    Periodicidade_ID: INTEGER <<FK>> NOT NULL
    Plantacao_ID: INTEGER <<FK>> NOT NULL
    Quantidade: NUMBER NOT NULL
}

entity Periodicidade {
    * ID: INTEGER <<PK>>
    --
    Designacao: VARCHAR2(255) NOT NULL UNIQUE
}

entity Plano_Rega {
    * Plano_ID: INTEGER <<PK>> <<FK>>
    --
}

entity Plano_Aplicacao_Fator_Producao {
    * Plano_ID: INTEGER <<PK>> <<FK>>
    --
}
entity PistaAuditoria{
    * ID: INTEGER <<PK>>
    Campo_ID: INTEGER <<PK>> <<FK>>
    --
    HoraRealizada: DATE NOT NULL
    Utilizador: VARCHAR2(255) NOT NULL
    Tabela: VARCHAR2(255) NOT NULL
    TipoAlteracao: VARCHAR2(7) NOT NULL
}


Campo ||-d-|{ Plantacao
Campo ||-u-|{ Restricao
Campo ||-u-|{ PistaAuditoria

Cultura ||-r-|{ Plantacao

Plantacao ||-r-|{ Accao
Plantacao ||-d-|{ Plano

Accao ||--d--|| Rega
Accao ||--d--|| Aplicacao_Fator_Producao
Accao ||--d--|| Adubacao

Metodo_Distribuicao ||-r-o{ Rega
Metodo_Distribuicao ||-l-o{ Aplicacao_Fator_Producao
Metodo_Distribuicao ||-u-o{ Adubacao

Tipo_Fator_Producao ||-l-o{ Fator_Producao
Categoria ||-d-o{ Substancia

Fator_Producao ||-d-|| Ficha_Tecnica
Fator_Producao ||--u--o{ Aplicacao_Fator_Producao
Fator_Producao ||--d--o{ Restricao

Ficha_Tecnica ||-d-|{ Ficha_Tecnica_Substancia

Substancia ||-u-|{ Ficha_Tecnica_Substancia

Periodicidade ||-r-o{ Plano

Plano_Rega ||-u-|| Plano

Plano_Aplicacao_Fator_Producao ||-u-|| Plano

Cultura ||-d-|| Cultura_Temporaria
Cultura ||-r-|| Cultura_Permanente

@enduml